HOST=$(shell hostname)
OBJS = $(addsuffix .o, $(basename $(wildcard *.cpp)))




#Greg: convenience for making remotely
ifeq ($(HOST),thinkpad)
REMOTE_DIR=/home/gregm/fitting/NPR/G1_NPR/analysis_cpp
REMOTE_HOST=qcd

all:
	@echo Making remotely
	rsync -az --delete ./ $(REMOTE_HOST):$(REMOTE_DIR)/
	ssh $(REMOTE_HOST) 'cd $(REMOTE_DIR); make'
	rsync -az cuth:$(REMOTE_DIR)/ ./

else

CXX = g++
#CXXFLAGS = -O2 -fno-strict-aliasing -std=c++11 -Wall -Wmissing-braces -Werror -fopenmp
CXXFLAGS = -O2 -fno-strict-aliasing -std=c++11 -Wall -Wmissing-braces -fopenmp
#CXXFLAGS = -g -fno-strict-aliasing -std=c++11 -Wall -Wmissing-braces -Werror -fopenmp 

all: $(OBJS)
	$(CXX) $(CXXFLAGS) -o npr.x $(OBJS)

AutogeneratedContractions_WithG1_WithSubtractions.cpp: write_contractions_code_withG1_withsubtractions.py
	./write_contractions_code_withG1_withsubtractions.py > AutogeneratedContractions_WithG1_WithSubtractions.cpp

endif

clean:
	-rm -f $(OBJS)
	-rm npr.x
	

